"use client";

/**
 * Client-side PDF export.
 *
 * jsPDF is loaded dynamically so the ~350 kB library never enters the initial
 * bundle — it only arrives when somebody actually clicks Export. Server-side
 * generation for scheduled/delivered reports lives in /api/report/generate.
 */

export interface PdfOptions {
  title: string;
  subtitle?: string;
  filename: string;
  /** DOM id of the region to describe; used for the page footer reference. */
  elementId?: string;
  /** Key/value rows rendered as a summary table. */
  summary?: [string, string][];
  /** Optional extra tabular section. */
  table?: { heading: string; columns: string[]; rows: (string | number)[][] };
}

const BRAND = { r: 33, g: 82, b: 255 }; // gradients.info.main #2152ff
const DARK = { r: 52, g: 71, b: 103 }; // dark.main #344767
const MUTED = { r: 103, g: 116, b: 142 }; // text.main #67748e

export async function exportDashboardPdf(options: PdfOptions): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4", orientation: "portrait" });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 48;
  let y = 0;

  /* ---------- header band ---------- */
  doc.setFillColor(BRAND.r, BRAND.g, BRAND.b);
  doc.rect(0, 0, pageWidth, 104, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("DataPulse Analytics", margin, 48);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Business intelligence for East African organisations", margin, 66);
  doc.text(
    new Date().toLocaleString("en-KE", { dateStyle: "long", timeStyle: "short" }),
    pageWidth - margin,
    66,
    { align: "right" }
  );

  y = 144;

  /* ---------- title ---------- */
  doc.setTextColor(DARK.r, DARK.g, DARK.b);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  const titleLines = doc.splitTextToSize(options.title, pageWidth - margin * 2);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 20;

  if (options.subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(MUTED.r, MUTED.g, MUTED.b);
    const subLines = doc.splitTextToSize(options.subtitle, pageWidth - margin * 2);
    doc.text(subLines, margin, y + 4);
    y += subLines.length * 14 + 10;
  }

  /* ---------- summary table ---------- */
  if (options.summary?.length) {
    y += 14;
    doc.setDrawColor(222, 226, 230); // grey[300]
    doc.setLineWidth(0.8);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(MUTED.r, MUTED.g, MUTED.b);
    doc.text("SUMMARY", margin, y);
    y += 12;
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;

    options.summary.forEach(([label, value]) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(MUTED.r, MUTED.g, MUTED.b);
      doc.text(label, margin, y + 12);

      doc.setFont("helvetica", "bold");
      doc.setTextColor(DARK.r, DARK.g, DARK.b);
      doc.text(String(value), pageWidth - margin, y + 12, { align: "right" });

      y += 24;
      doc.setDrawColor(233, 236, 239); // grey[200]
      doc.line(margin, y, pageWidth - margin, y);
    });
    y += 18;
  }

  /* ---------- optional table ---------- */
  if (options.table) {
    const { heading, columns, rows } = options.table;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(MUTED.r, MUTED.g, MUTED.b);
    doc.text(heading.toUpperCase(), margin, y);
    y += 14;

    const autoTable = (await import("jspdf-autotable")).default;
    autoTable(doc, {
      startY: y,
      head: [columns],
      body: rows.map((r) => r.map(String)),
      margin: { left: margin, right: margin },
      styles: { font: "helvetica", fontSize: 9, cellPadding: 6, textColor: [103, 116, 142] },
      headStyles: {
        fillColor: [52, 71, 103],
        textColor: [255, 255, 255],
        fontStyle: "bold",
        fontSize: 8,
      },
      alternateRowStyles: { fillColor: [248, 249, 250] },
      theme: "grid",
    });
  }

  /* ---------- footer on every page ---------- */
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(173, 181, 189); // grey[500]
    doc.text(
      "Generated by DataPulse Analytics · datapulse.co.ke · Figures are estimates where labelled",
      margin,
      pageHeight - 28
    );
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 28, {
      align: "right",
    });
  }

  doc.save(options.filename);
}
